name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  automerge:
    # 仅处理 dependabot[bot] 提交的 PR
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      # 1. 自动批准 PR
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # 2. 启用 Auto-merge（可选 merge-method：merge / squash / rebase）
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

permissions:
  contents: read
  pull-requests: write
